labs12-real-estate/labs12-real-estate-FE

LICENSE, README.md, src/App.js, src/index.js
- added license
- fixed breaking changes for deployment
=> Added license, fixed breaking bugs for deployment

.eslintrc.json, .prettierrc.json, AppNotes/fileStructure.md, README.md, src/App.js, src/index.js, src/reducers/authReducer.js, src/reducers/houseReducer.js, src/reducers/index.js, src/reducers/userReducer.js
changed ESLINT/prettier settings, 
added redux boilerplate
=> JS - changed ESLINT/prettier settings, added redux boilerplate

src/App.js, src/components/buttons/Button.js, src/components/navigation/LandingTopBar.js, src/index.js, src/styles/_landingTopBarStyles.scss, src/styles/_reset.scss, src/styles/index.scss, src/views/LandingPage.js
Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
- Added styles folder to src
- added reset.scss
- added index.scss
- added landingPageTopBarStyles.scss
- added jsx to get beginning structure to LandingPage top bar
- added button jsx to Button
- added background to body {
} (NOTE: Gabe to fix gradient)
- [X ] New feature (non-breaking change which adds functionality)
- [X ] Complete, tested, ready to review and merge
- [X ] My …
=> Jordan Stoddard - Added styles folder to src, added reset, added index.scss, added styles folder for landingTopBar

src/components/inputs/AddressInput.js
=> add AddressInput component for landing page use 

AppNotes/attributions.md, src/components/dashboardContent/overviewContent/OverviewContent.js, src/dummy-data-structures/dashboard-sidebar-data.js, src/styles/_dashboardSideBarStyles.scss, src/styles/_landingHeroStyles.scss, src/views/LandingPage.js, src/views/OverviewPage.js
- Renamed overview container component.
- Removed AddressInput from landing page (was there for demo purposes)
- Added styles to the active dashboard sidebar nav item.
- Added a file for storing attributions for content used from third parties. …
=> Jordan Stoddard - Removing AddressInput from landing page(was here for demo purposes only), added styles to dashboard sidebar

src/components/inputs/AddressInput.js, src/components/inputs/AddressInputArchived.js
- [] Test A
- [] Test B
- [] My code has been reviewed by at least one peer
- [] I have made corresponding changes to the documentation
- [] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally …
=> refactor AddressInput using hooks

src/components/cards/MarketingCard.js, src/components/cards/ReviewCard.js, src/components/footer/Footer.js, src/components/inputs/AddressInput.js, src/helper-functions/display-functions.js, src/styles/_landingBodyStyles.scss, src/styles/_landingHeroStyles.scss, src/styles/_landingTopBarStyles.scss, src/styles/_mixins.scss, src/views/LandingPage.js
Completed features:
- Hero section
- Added a laptop image with a screenshot of MyHouse's dashboard
- Marketing Cards
- Bottom CTA section
- Footer - logo scrolls back to top on click (snaps to top, doesn't animate)
- Refactored some JSX to use more semantic tags
- Added max-width to content
- Added a `MarketingCard.js` component
- Added a `scrollToTop` function to `helper-fucnions/display-functions` 
=> Gabe samaniego - Landing page desktop view 95%

amplify/backend/api/labs12realestatefe/schema.graphql, src/actions/houseActions.js, src/actions/index.js, src/graphql/mutations.js, src/graphql/queries.js, src/graphql/schema.json, src/graphql/subscriptions.js, src/reducers/houseReducer.js
This will update the schema to include all data points in our canvas document, as well as all data that we can expect to get from the DS backend.
=> Update schema: include parcel data and more user data

src/components/cards/FeatureCard.js, src/components/dashboardContent/overviewContent/CardsContainer.js, src/components/dashboardContent/overviewContent/OverviewContent.js, src/components/jumbotrons/DashboardJumbo.js, src/helper-functions/display-functions.js, src/reducers/houseReducer.js, src/styles/_dashboardOverviewStyles.scss, src/styles/_dashboardPageGeneralStyles.scss, src/views/OverviewPage.js
- [] Test A
- [] Test B
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit …
=> David Lam - add Overview page, render data from AWS

src/actions/authActions.js, src/actions/index.js, src/components/inputs/RegisterInput.js, src/reducers/authReducer.js
This adds the `RegisterInput` component and Redux actions for `signUp` and `confirmSignUp`.
**Todo:** Better error handling, and refactor `RegisterInput` to sub-components.
=> Add registration component and functionality

src/components/dashboardContent/valuationPlaygroundContent/ValuationPlaygroundContent.js, src/components/jumbotrons/DashboardJumbo.js, src/styles/_dashboardOverviewStyles.scss, src/styles/_dashboardPageGeneralStyles.scss, src/styles/_reset.scss, src/styles/_valuationPlaygroundStyles.scss
Overview dashboard:
- Updated styling (fonts, alignment, lighter drop shadows)
Valuation playground: 
- Updated upgrade results w/ Anthony's help
- Select feature (one upgrade at a time)
- Added responsiveness to select bars and to jumbotron
Other:
- Added 2 more design files (form wizard welcome and confirmation pages)
=> Gabe Samaniego - Valuation PG, Overview, & form wizard design files

src/components/wizardForm/WizardFormInitialData.js, src/components/wizardForm/WizardFormProgress.js, src/styles/_wizardFormStyles.scss, src/styles/index.scss, src/views/WizardFormPage.js
All components of `WizardFormPage` view are fully functional.
Co-authored-by: DavidLam89 <davidlamsgn@gmail.com>
=> Integrate all parts of WizardFormPage, add initial layout styles

AppNotes/Designs.md, src/components/dashboardContent/mortgageCalculatorContent/MortgageCalculatorContent.js, src/styles/_dashboardMortgageCalculatorStyles.scss, src/styles/index.scss
I almost forgot how to commit, it has been so long!!
First commit :)))))
=> Adds mortgage calculator and styling to containing div

src/components/dashboardContent/valuationPlaygroundContent/ValuationPlaygroundSelector.js, src/styles/_valuationPlaygroundStyles.scss
- Created highlight effect using conditional styling
- Intends to communicate to the user that only 1 upgrade can be selected at a time.
- Hides currently selected option from dropdown
- Added a key prop to list of options to clear console errors
=> Gabe Samaniego - Select feature in Valuation Playground

src/App.js, src/actions/authActions.js, src/actions/index.js, src/components/dashboardContent/overviewContent/CardsContainer.js, src/components/inputs/LoginInput.js, src/components/navigation/DashboardTopBar.js, src/reducers/authReducer.js
- Changed CardsContainer to simply start with a CardsArray rather than pushing objects into cardsArray.
- Added a useEffect CDM to App.js to check if the user is logged in by checking the Auth.currentSession()
- Added types to implement this feature using Redux.
- Added actions to implement this feature using Redux.
- Added logic and cases to authReducer to implement this feature using Redux.
Please describe the …
=> Jordan Stoddard - Checks for LoggedIn Session/State PR

amplify/backend/api/labs12realestatefe/schema.graphql, src/actions/authActions.js, src/components/inputs/AddressInput.js, src/components/inputs/RegisterInput.js, src/components/wizardForm/WizardFormConfirmation.js, src/components/wizardForm/WizardFormInitialData.js, src/graphql/mutations.js, src/graphql/queries.js, src/graphql/schema.json, src/graphql/subscriptions.js, src/helper-functions/toHouseInput.js, src/views/WizardFormPage.js
This makes the new user registration flow fully functional from landing page to wizard form to sign-up and ending in overview of the newly created house. Manually tested end-to-end.
=> Connect wizard form to landing page and to user registration

src/actions/authActions.js, src/actions/houseActions.js, src/actions/index.js, src/components/inputs/LoginInput.js, src/components/inputs/RegisterInput.js, src/reducers/authReducer.js, src/reducers/houseReducer.js, src/views/OverviewPage.js
This removes some errors that were being thrown in the user registration flow, also passes history into Redux actions.
=> Bugfix and refactor of house and auth actions

amplify/backend/api/labs12realestatefe/schema.graphql, src/graphql/schema.json, yarn.lock
Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> Bugfix: update schema

src/components/cards/FeatureCard.js, src/components/dashboardContent/overviewContent/CardsContainer.js, src/components/inputs/LoginInput.js, src/components/navigation/DashboardTopBar.js, src/helper-functions/display-functions.js, src/helper-functions/onClick-logic.js, src/styles/_dashboardOverviewStyles.scss, src/styles/_mixins.scss
- Added alt attribute to feature card images.
- Added a function to convert lot sq ft to acres.
- Abstracted out handleSignIn and handleSignOut functions.
- Login button does not render if in wizard form.
- Added default media breakpoints to mixins.scss
- Reduced margin-top on .value class.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list …
=> Jordan Stoddard - Conditional Rendering/Styles PR

src/components/dashboardContent/mortgageCalculatorContent/MortgageCalculator.js, src/styles/_dashboardMortgageCalculatorStyles.scss, src/styles/_dashboardPageGeneralStyles.scss, src/styles/_dashboardSideBarStyles.scss
Mortgage calculator:
- Restructured JSX elements
- Styled input fields
- Styled line chart
- Cleaned up class names and removed unused classes
Dashboard:
- Made sidebar slimmer
=> Gabe & Anthony - Mortgage Calculator desktop view done

src/components/footer/Footer.js, src/components/inputs/AddressInput.js, src/components/landingPageContent/LandingBottomCTA.js, src/components/landingPageContent/LandingHero.js, src/components/landingPageContent/LandingMiddle.js, src/components/landingPageContent/LandingReviews.js, src/components/navigation/DashboardTopBar.js, src/helper-functions/display-functions.js, src/helper-functions/onClick-logic.js, src/styles/_footerStyles.scss, src/styles/_landingBodyStyles.scss, src/styles/_landingHeroStyles.scss, src/styles/_landingTopBarStyles.scss, src/styles/index.scss, src/views/LandingPage.js
- Made the 'Team' span a Link inside footer.
- added a container div for styling inside AddressInput
- Added LandingBottomCTA component for modularity inside landing page.
- Added LandingHero component for modularity inside landing page.
- Added LandingMiddle component for modularity inside landing page.
- Added LandingReviews component for modularity inside landing page.
- moved scrollToTop function from display-functions.js to onClick-logic.js
- added styles for 100% responsiveness of landing page
- [] Complete, but not …
=> Jordan Stoddard - Landing page 100% responsive PR

src/components/dashboardContent/overviewContent/OverviewContent.js, src/components/navigation/DashboardTopBar.js, src/components/navigation/SideBar.js, src/styles/_dashboardPageGeneralStyles.scss, src/styles/_dashboardSideBarStyles.scss, src/styles/_dashboardTopBarStyles.scss, src/styles/_variables.scss, src/styles/index.scss, src/views/DashboardContainer.js, src/views/DesignStudioPage.js, src/views/MortgageCalculatorPage.js, src/views/MyHousePage.js, src/views/OverviewPage.js, src/views/ValuationPlaygroundPage.js
This will change the sidebar component (in the dashboard views) to act as a drawer, including a hamburger menu for toggling. Also switches between showing home icon and heading.
=> Add sidebar drawer and change navbar at mobile view

src/components/dashboardContent/mortgageCalculatorContent/Chart.js, src/components/dashboardContent/mortgageCalculatorContent/MortgageCalculator.js, src/components/footer/Footer.js, src/styles/_dashboardMortgageCalculatorStyles.scss
- Made x and y of  SVG inside Chart component dynamic based on windowWidth
- Added styles to make Mortgage Calculator 100% responsive
- Added copyright symbol to footer.
- [] Test B
- [] My code has been reviewed by at least one peer
- [] I have …
=> Jordan Stoddard - Mortgage Calculator 100% Responsive PR

src/views/DashboardContainer.js
This resolves a merge conflict from two previous PRs.
=> Bugfix: merge logic for DashboardContainer

src/components/dashboardContent/homeProfileContent/HouseProfileForm.js, src/helper-functions/display-functions.js, src/styles/_dashboardHomeProfileStyles.scss, src/styles/_variables.scss, src/styles/index.scss
This adds basic styling and markup for the ProfileForm page text editor inputs.
=> Profile form: basic styling/markup

src/components/inputs/ForgotPasswordInput.js, src/components/inputs/LoginInput.js, src/components/inputs/RegisterInput.js, src/components/inputs/SetNewPasswordInput.js, src/dummy-data-structures/team-info.js, src/helper-functions/error-handling-functions.js, src/reducers/authReducer.js, src/styles/_modalStyles.scss, src/styles/inlineStyles/modalStyles.js
- Error handling for ForgotPassword functionality complete.
- Changed Jordan's picture on Team Page
- added helper functions for displaying errors in LoginModal/ForgotPassword Inputs.
- Fixed merge conflict in AuthReducer
- Changed some styles to support more uniform error message handling in LoginModal/ForgotPassword Inputs.
- Added styles for the closeIcon in LoginModal.
Please describe the tests that you ran to verify your …
=> Jordan Stoddard - LoginModal/ForgotPasswordInput error handling PR

package.json, src/components/footer/Footer.js, src/components/inputs/AddressInput.js, src/components/landingPageContent/LandingBottomCTA.js, src/components/landingPageContent/LandingHero.js, src/components/navigation/DashboardTopBar.js, src/components/navigation/LandingTopBar.js, src/components/wizardForm/WizardFormInitialData.js, src/helper-functions/display-functions.js, src/styles/_dashboardTopBarStyles.scss, src/styles/_landingHeroStyles.scss, src/styles/_landingTopBarStyles.scss, src/styles/_wizardFormStyles.scss, src/styles/inlineStyles/navStickyStyles.js, yarn.lock
- Add react scroll
- When click MyHouse link in Footer or LandingBottomCTA bottom scroll smoothly to top of screen.
- Added welcome text and made it more readable on page 1 of wizard form.
- added styles to dashboard navbar and made it look good at all view ports.
- changed landingpage topbar and landingpage hero to match new aesthetic and 100% responsive.
- Added fetching state render to get started button.
- Added function useWindowScrollY to calculate location of scroll.
- Made LandingTopBar conditionally sticky if off-set from top of page.
- [] This change requires a documentation …
=> Jordan Stoddard - Landing Page & Form Wizard Style Changes PR

src/dummy-data-structures/team-info.js
Adding my section to team info page
=> Add to team info

src/actions/authActions.js, src/index.js, src/styles/_reset.scss
- Adds and configures react-toastify
- Added a toast within forgot password stage 2 success.
- Added place to style toastify messages.
- [] New feature (non-breaking change which adds functionality)
- [] Complete, tested, ready to review and merge
- [] Test A
- …
=> Jordan Stoddard - React-Toastify PR

package.json, src/actions/authActions.js, src/components/navigation/SideBarNavItem.js, src/components/wizardForm/WizardFormInitialData.js, src/dummy-data-structures/dashboard-sidebar-data.js, src/helper-functions/react-joyride-steps-data.js, src/styles/_dashboardJoyRideStyles.scss, src/styles/_reset.scss, src/styles/_toastifyMessageStyles.scss, src/styles/_valuationPlaygroundStyles.scss, src/styles/index.scss, src/styles/inlineStyles/navStickyStyles.js, src/views/LandingPage.js, src/views/OverviewPage.js, yarn.lock
- change structure for react-toastify styles
- add an 'id' attribute to navItem div for targeting
- Add a flag to local storage to note that user is coming from form wizard to overviewpage
- create steps array and useStep custom hook to abstract logic for React.
- create style file for ReactJoyRide components
- Decreased height of VPG selector container so all selectors match total height of VPG jumbo
- fix z-index for landingpage top bar
- clear registering flag when navigate to LandingPage
- add ReactJoyRide component to OverviewPage
- [] …
=> Jordan Stoddard - React JoyRide PR

src/actions/storageActions.js, src/components/cards/FeatureCard.js, src/components/dashboardContent/designStudioContent/ImageCard.js, src/components/dashboardContent/settingsPageContent/sections/AttributesForm.js, src/components/dashboardContent/settingsPageContent/sections/ErrorContainer.js, src/components/dashboardContent/settingsPageContent/sections/NewPasswordForm.js, src/components/dashboardContent/settingsPageContent/sections/UserInfo.js, src/reducers/storageReducer.js, src/styles/_dashboardSettingsStyles.scss, src/styles/_dashboardTopBarStyles.scss, src/styles/_footerStyles.scss, src/styles/_landingBodyStyles.scss, src/styles/_landingHeroStyles.scss, src/styles/_landingTopBarStyles.scss, src/styles/_modalStyles.scss, src/styles/_reset.scss, src/styles/_wizardFormStyles.scss, src/views/LandingPage.js
- Added a loader-spinner during fetching state to Sq Ft in Feature Card
- added an && gate to current to make sure Design Studio doesn't crash if current.clientHeight hasn't populated yet.
- Made settings page 100% responsive.
- Changed ErrorContainer to be a ternary rather than a && gate.
- Made comment within code on LandingPage to be more understandable.
- Changed active and hover states of all pink buttons to have more pink active and hover states.
Please describe the tests that …
=> Jordan Stoddard - UI/UX fixes

src/actions/authActions.js, src/assets/icons/UserPlaceholder.js, src/components/dashboardContent/homeProfileContent/Backdrop.js, src/components/dashboardContent/homeProfileContent/UserProfileSection.js, src/components/dashboardContent/settingsPageContent/sections/ErrorContainer.js, src/styles/_houseProfileStyles.scss
This adds image upload functionality and a camera overlay to the `Profile` view for both the backdrop image and the user profile image (avatar).
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.
=> Add upload functionality and camera overlay

src/actions/storageActions.js, src/components/dashboardContent/homeProfileContent/Backdrop.js, src/components/dashboardContent/homeProfileContent/Gallery.js, src/components/dashboardContent/homeProfileContent/MyHouseContent.js, src/components/dashboardContent/homeProfileContent/UserProfileSection.js, src/styles/_houseProfileStyles.scss
This will add the `Gallery` component to the `HouseProfile` view. Still need a few things, but gallery image upload functionality is in place.
**Todo:**
- Optimistic update of UI (user shouldn't need to refresh page)
- Use `loading-skeleton`
- Add modal for full-size images
- Show ⓧ `onHover` for each image to delete
- Show 🔍 overlay `onHover` to indicate each image can be expanded to full size
- Toast message for images that are too large/error handling
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.
=> Add Gallery UI

package.json, src/helper-functions/form-logic-functions.spec.js, yarn.lock
These are unit tests I had already written for `src/helper-functions/form-logic-functions.js`.
=> Adding unit tests for form functions

src/graphql/__tests__/appsync.spec.js
Minimal AppSync tests for sign in, sign up, and house query. (Not testing any mutative/destructive behavior unless I can find out how to setup a separate testing DB while keeping our current schema).
=> Add AppSync integration tests
